[project]
name = "econterm"
version = "0.0.1"
description = "a FRED research CLI with from-scratch regression analysis"
readme = "README.md"
requires-python = ">=3.10,<4.0"
authors = [
    {name = "Ian Darby", email = "ian.lee.darby@gmail.com"}
]
dependencies = [
    "httpx",
    "numpy",
    "matplotlib",
    "click",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "statsmodels",
    "respx",
    "mypy",
    "dotenv",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"